"""
Django settings for HidroPlan project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

from django.contrib.messages import constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-oury_nywb(w*hn@qyba6p^sap+o5a*izjh!h)%ofmcor#0m$$h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'HidroPlanApp',
    'Registros',
    'Lechuga',
    'Betabel',
    'Espinaca',
    'Autenticacion',
    'DatosPersonales',
    'crispy_forms',
    'crispy_bootstrap4',
    'pwa',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'HidroPlan.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HidroPlan.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'hidroponico',
        'USER': 'admin',
        'PASSWORD': 'mydatabaseRDS',
        'HOST': 'bddjango.ces2xbpzw8uh.us-east-1.rds.amazonaws.com',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

"""DATE_INPUT_FORMATS = (
    '%d/%m/%Y',  # '21/03/2014'
)"""

CRISPY_TEMPLATE_PACK='bootstrap4'

MESSAGE_TAGS={
    constants.DEBUG: 'debug',
    constants.INFO: 'info',
    constants.SUCCESS: 'success',
    constants.WARNING: 'Warning',
    constants.ERROR: 'danger',
}


# Configuración de Firebase
''''
FIREBASE_CONFIG = {
    "apiKey": "AIzaSyC0zz9fWUNpFZzI5MphzsVPBUJmz7w8igo",
    "authDomain":  "notificaciones-ed05c.firebaseapp.com",
    "databaseURL": "TU_DATABASE_URL",
    "projectId": "notificaciones-ed05c",
    "storageBucket": "TU_STORAGE_BUCKET""notificaciones-ed05c.appspot.com",
    "messagingSenderId":  "221105754482",
    "appId": "1:221105754482:web:34dae1a8fe1f5035988deb",

}'''
#configuracion para envio de correos con gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'orlandoquirogam@gmail.com'  # Coloca aquí tu dirección de correo de Gmail
EMAIL_HOST_PASSWORD = 'tzcabjgbgcsphafo'    # Coloca aquí la contraseña de tu cuenta de Gmail

PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR,'serviceworker.js')