# Generated by Django 4.1.7 on 2023-08-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betabel', '0002_alter_cultivob_ph_alter_cultivob_temperatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivob',
            name='nombreRegistro',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
