# Generated by Django 4.1.7 on 2023-06-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cultivoE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaSiembra', models.DateField()),
                ('fechaGerminacion', models.DateField()),
                ('fechaTrasplante', models.DateField()),
                ('fechaCosecha', models.DateField()),
                ('cantPlantas', models.IntegerField()),
                ('kgAproxCosecha', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ph', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('idUsuario', models.IntegerField()),
            ],
            options={
                'verbose_name': 'registro',
                'verbose_name_plural': 'registros',
            },
        ),
    ]
