# Generated by Django 4.1.7 on 2023-08-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Espinaca', '0002_alter_cultivoe_ph_alter_cultivoe_temperatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivoe',
            name='nombreRegistro',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
